name: quality_fruit_app
description: "Sistema de Controle de Qualidade de Frutas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # Fontes Google
  google_fonts: ^6.1.0
  
  # Banco de dados SQLite
  sqflite: ^2.3.0
  
  # Geração de UUIDs
  uuid: ^4.5.1
  
  # Cache e preferências locais
  shared_preferences: ^2.2.2
  
  # Acesso aos diretórios do sistema
  path_provider: ^2.1.1
  
  # Manipulação de caminhos
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
